---
# image will be published to ghcr.io/maximizerr/sway-base-enhanced
name: sway-enhanced

description: Fedora Sway with enhanced default settings

base-image: ghcr.io/wayblueorg/sway
image-version: latest

modules:
    - from-file: common/common-modules.yml
    - from-file: sway-enhanced/.import_all.yml
    - from-file: manjaro-sway/.import_all.yml
