---
# image will be published to ghcr.io/maximizerr/sway-base-enhanced
name: sway-base-enhanced

description: Fedora Sway with enhanced default settings

base-image: ghcr.io/wayblueorg/sway
image-version: latest

modules:
    - from-file: common-modules.yml
    - from-file: swayosd/install-rpm.yml
