stages:
  - name: swayosd
    from: docker.io/library/rust:latest
    modules:
      - type: script
        snippets:
          - apt-get update && apt-get install -y libglib2.0-dev sassc libudev-dev libevdev-dev libgtk-3-dev libgtk-layer-shell-dev libpulse0 libinput-dev meson cargo git libgtk4-layer-shell-dev wget #Install builddep
          - wget http://ftp.fr.debian.org/debian/pool/main/g/gtk4-layer-shell/libgtk4-layer-shell-dev_1.0.4-1_amd64.deb
          - wget http://ftp.fr.debian.org/debian/pool/main/g/gtk4-layer-shell/gir1.2-gtk4layershell-1.0_1.0.4-1_amd64.deb
          - dpkg -i gir1.2-gtk4layershell-1.0_1.0.4-1_amd64.deb
          - dpkg -i libgtk4-layer-shell0_1.0.4-1_amd64.deb 
          - git clone https://github.com/ErikReider/SwayOSD.git
          - cd SwayOSD && meson setup build && ninja -C build
          - mkdir -p /out/swayosd/bin && mv build/src/swayosd-* /out/swayosd/bin/. && mv build/data /out/swayosd/. && mv data/udev /out/swayosd/. && mv data/polkit /out/swayosd/. # Move bin and runtime

modules:
  # Copy the bin and runtime from the `helix` stage
  - type: copy
    from: swayosd
    src: /out/swayosd/bin/
    dest: /usr/bin/
  - type: copy
    from: swayosd
    src: /out/swayosd/data/style.css
    dest: /etc/xdg/swayosd/style.css
  - type: copy
    from: swayosd
    src: /out/swayosd/data/swayosd-libinput-backend.service
    dest: /etc/systemd/system/swayosd-libinput-backend.service
  - type: copy
    from: swayosd
    src: /out/swayosd/udev/99-swayosd.rules
    dest: /etc/udev/rules.d/99-swayosd.rules
  - type: copy
    from: swayosd
    src: /out/swayosd/data/org.erikreider.swayosd.service
    dest: /etc/dbus-1/system-services/org.erikreider.swayosd.service
  - type: copy
    from: swayosd
    src: /out/swayosd/dbus/org.erikreider.swayosd.conf
    dest: /etc/dbus-1/system.d/org.erikreider.swayosd.conf
  - type: copy
    from: swayosd
    src: /out/swayosd/polkit/actions/org.erikreider.swayosd.policy.in
    dest: /etc/polkit-1/actions/org.erikreider.swayosd.policy
  - type: copy
    from: swayosd
    src: /out/swayosd/polkit/rules/org.erikreider.swayosd.rules
    dest: /etc/polkit-1/rules.d/org.erikreider.swayosd.rules

  - type: systemd
    system:
      enabled:
        - swayosd-libinput-backend.service
