modules:
  - from-file: SwayAura/sway.yml
  - from-file: SwayAura/waybar.yml
  - from-file: SwayAura/sddm.yml
  - from-file: SwayAura/rofi.yml
  - from-file: SwayAura/backgrounds.yml
  - from-file: SwayAura/swayosd.yml
  - from-file: SwayAura/cursor.yml
  - from-file: SwayAura/wayland-displays.yml
